//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalServices
    {
        public AdditionalServices()
        {
            this.BookingServices = new HashSet<BookingServices>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public decimal ServicePrice { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BookingServices> BookingServices { get; set; }
    }
}
