//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircrafts
    {
        public Aircrafts()
        {
            this.Flights = new HashSet<Flights>();
            this.Seats = new HashSet<Seats>();
        }
    
        public int AircraftId { get; set; }
        public string Model { get; set; }
        public int TotalSeats { get; set; }
        public int BusinessClassSeats { get; set; }
        public int ComfortClassSeats { get; set; }
        public int EconomyClassSeats { get; set; }
    
        public virtual ICollection<Flights> Flights { get; set; }
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
