//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public Bookings()
        {
            this.BaggageReceipts = new HashSet<BaggageReceipts>();
            this.BookingServices = new HashSet<BookingServices>();
            this.FlightSeats = new HashSet<FlightSeats>();
            this.Insurance = new HashSet<Insurance>();
            this.Passengers = new HashSet<Passengers>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int FlightId { get; set; }
        public int ClassId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public decimal TotalPrice { get; set; }
        public string Status { get; set; }
        public bool IsOperatorBooking { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<BaggageReceipts> BaggageReceipts { get; set; }
        public virtual Flights Flights { get; set; }
        public virtual Operators Operators { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<BookingServices> BookingServices { get; set; }
        public virtual ICollection<FlightSeats> FlightSeats { get; set; }
        public virtual ICollection<Insurance> Insurance { get; set; }
        public virtual ICollection<Passengers> Passengers { get; set; }
    }
}
