//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public Flights()
        {
            this.Bookings = new HashSet<Bookings>();
            this.FlightSeats = new HashSet<FlightSeats>();
        }
    
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
        public int DepartureAirportId { get; set; }
        public int ArrivalAirportId { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public int AircraftId { get; set; }
        public decimal BasePrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<FlightSeats> FlightSeats { get; set; }
    }
}
