//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSeats
    {
        public int FlightSeatId { get; set; }
        public int FlightId { get; set; }
        public int SeatId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public bool IsOccupied { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Flights Flights { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
