//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int InsuranceId { get; set; }
        public int BookingId { get; set; }
        public string InsuranceType { get; set; }
        public decimal Price { get; set; }
        public string Details { get; set; }
    
        public virtual Bookings Bookings { get; set; }
    }
}
