//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIRCORE_DIPLOM_01Entities : DbContext
    {
        public AIRCORE_DIPLOM_01Entities()
            : base("name=AIRCORE_DIPLOM_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdditionalServices> AdditionalServices { get; set; }
        public DbSet<Aircrafts> Aircrafts { get; set; }
        public DbSet<Airports> Airports { get; set; }
        public DbSet<BaggageReceipts> BaggageReceipts { get; set; }
        public DbSet<Bookings> Bookings { get; set; }
        public DbSet<BookingServices> BookingServices { get; set; }
        public DbSet<Flights> Flights { get; set; }
        public DbSet<FlightSeats> FlightSeats { get; set; }
        public DbSet<Insurance> Insurance { get; set; }
        public DbSet<Operators> Operators { get; set; }
        public DbSet<Passengers> Passengers { get; set; }
        public DbSet<Seats> Seats { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
