//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int PassengerId { get; set; }
        public int BookingId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual Bookings Bookings { get; set; }
    }
}
