//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public Seats()
        {
            this.FlightSeats = new HashSet<FlightSeats>();
        }
    
        public int SeatId { get; set; }
        public int AircraftId { get; set; }
        public string SeatNumber { get; set; }
        public int ClassId { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual ICollection<FlightSeats> FlightSeats { get; set; }
    }
}
