//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceClasses
    {
        public ServiceClasses()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Seats = new HashSet<Seats>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public decimal PriceMultiplier { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
